Add support for the github_app_installation_repository resource
mineiros-io/terraform-github-repository pull request #120
Opened 2022-05-03 09:58 UTC by soerenmartius

2022-05-03 20:01 UTC, anthr76 commented
Closes 119

2022-05-04 11:04 UTC, mariux requested changes

2022-05-04 11:04 UTC, mariux commented on main.tf
> +  for_each = { for a in var.app_installations : a => a }
that's a noop...

```suggestion
  for_each = var.app_installations
```

2022-05-04 11:51 UTC, mariux approved these changes
lgtm

2022-05-04 12:13 UTC, merged